package rs.ac.bg.fon.nprog.client.forms;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

public class FrmKurs extends JDialog {

	/**
	 * Creates new form FrmKurs
	 */
	public FrmKurs(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lblNaziv = new javax.swing.JLabel();
		lblNivo = new javax.swing.JLabel();
		lblTipKursa = new javax.swing.JLabel();
		lblJezik = new javax.swing.JLabel();
		txtNaziv = new javax.swing.JTextField();
		cmbNivo = new javax.swing.JComboBox();
		cmbTipKursa = new javax.swing.JComboBox();
		cmbJezik = new javax.swing.JComboBox();
		pnlUnosTermina = new javax.swing.JPanel();
		lblDatumPocetka = new javax.swing.JLabel();
		lblDatumZavrsetka = new javax.swing.JLabel();
		lblRaspored = new javax.swing.JLabel();
		txtDatumPocetka = new javax.swing.JTextField();
		txtDatumZavrsetka = new javax.swing.JTextField();
		txtRaspored = new javax.swing.JTextField();
		lblKapacitet = new javax.swing.JLabel();
		lblBrojCasova = new javax.swing.JLabel();
		lblCena = new javax.swing.JLabel();
		txtKapacitet = new javax.swing.JTextField();
		txtBrojCasova = new javax.swing.JTextField();
		txtCena = new javax.swing.JTextField();
		lblGrad = new javax.swing.JLabel();
		cmbGrad = new javax.swing.JComboBox();
		lblAdresa = new javax.swing.JLabel();
		cmbAdresa = new javax.swing.JComboBox();
		lblProfesor = new javax.swing.JLabel();
		cmbProfesor = new javax.swing.JComboBox();
		pnlUnetiTermini = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblUnetiTermini = new javax.swing.JTable();
		btnDodajNoviTermin = new javax.swing.JButton();
		btnObrisiUnetiTermin = new javax.swing.JButton();
		btnIzmeniTermin = new javax.swing.JButton();
		btnPotvrdiIzmene = new javax.swing.JButton();
		btnSacuvaj = new javax.swing.JButton();
		btnOmoguciIzmene = new javax.swing.JButton();
		btnIzmeniKurs = new javax.swing.JButton();
		btnUnesiTermine = new javax.swing.JButton();
		btnIzaberiTermin = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Dodavanje novog kursa");

		lblNaziv.setText("Naziv:");

		lblNivo.setText("Nivo:");

		lblTipKursa.setText("Tip kursa:");

		lblJezik.setText("Jezik:");

		cmbNivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmbTipKursa.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		cmbJezik.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		pnlUnosTermina.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos termina kursa",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Tahoma", 0, 12))); // NOI18N

		lblDatumPocetka.setText("Datum pocetka:");

		lblDatumZavrsetka.setText("Datum zavrsetka:");

		lblRaspored.setText("Raspored:");

		lblKapacitet.setText("Kapacitet:");

		lblBrojCasova.setText("Broj casova:");

		lblCena.setText("Cena:");

		lblGrad.setText("Grad:");

		cmbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblAdresa.setText("Adresa:");

		cmbAdresa.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		lblProfesor.setText("Profesor:");

		cmbProfesor.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		pnlUnetiTermini.setBorder(javax.swing.BorderFactory.createTitledBorder("Uneti termini"));

		tblUnetiTermini
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblUnetiTermini);

		javax.swing.GroupLayout pnlUnetiTerminiLayout = new javax.swing.GroupLayout(pnlUnetiTermini);
		pnlUnetiTermini.setLayout(pnlUnetiTerminiLayout);
		pnlUnetiTerminiLayout.setHorizontalGroup(pnlUnetiTerminiLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(pnlUnetiTerminiLayout
						.createSequentialGroup().addContainerGap().addComponent(jScrollPane1).addContainerGap()));
		pnlUnetiTerminiLayout
				.setVerticalGroup(pnlUnetiTerminiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlUnetiTerminiLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnDodajNoviTermin.setText("Dodaj novi termin");

		btnObrisiUnetiTermin.setText("Obrisi uneti termin");

		btnIzmeniTermin.setText("Izmeni uneti termin");

		btnPotvrdiIzmene.setText("Potvrdi izmene");

		javax.swing.GroupLayout pnlUnosTerminaLayout = new javax.swing.GroupLayout(pnlUnosTermina);
		pnlUnosTermina.setLayout(pnlUnosTerminaLayout);
		pnlUnosTerminaLayout.setHorizontalGroup(pnlUnosTerminaLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlUnosTerminaLayout.createSequentialGroup().addContainerGap().addGroup(pnlUnosTerminaLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(pnlUnetiTermini, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(pnlUnosTerminaLayout.createSequentialGroup().addGroup(pnlUnosTerminaLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlUnosTerminaLayout.createSequentialGroup().addGroup(pnlUnosTerminaLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
												.addComponent(lblDatumPocetka).addGap(18, 18, 18)
												.addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE,
														140, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(lblDatumZavrsetka).addComponent(lblRaspored))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(txtRaspored,
																javax.swing.GroupLayout.PREFERRED_SIZE, 139,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(txtDatumZavrsetka,
																javax.swing.GroupLayout.PREFERRED_SIZE, 139,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(18, 18, 18)
										.addGroup(pnlUnosTerminaLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblBrojCasova).addComponent(lblCena)
												.addComponent(lblKapacitet)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										pnlUnosTerminaLayout.createSequentialGroup().addComponent(btnPotvrdiIzmene)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(btnIzmeniTermin)))
								.addGap(18, 18, 18)
								.addGroup(pnlUnosTerminaLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
																.addComponent(txtCena,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 97,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(lblProfesor))
														.addComponent(btnObrisiUnetiTermin,
																javax.swing.GroupLayout.PREFERRED_SIZE, 159,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(17, 17, 17)
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(cmbProfesor, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(btnDodajNoviTermin,
																javax.swing.GroupLayout.DEFAULT_SIZE, 152,
																Short.MAX_VALUE)))
										.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
																.addComponent(txtKapacitet,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 97,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(lblGrad))
														.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
																.addComponent(txtBrojCasova,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 97,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18).addComponent(lblAdresa)))
												.addGap(24, 24, 24)
												.addGroup(pnlUnosTerminaLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(cmbAdresa, 0,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))))))
						.addContainerGap()));
		pnlUnosTerminaLayout.setVerticalGroup(pnlUnosTerminaLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlUnosTerminaLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(pnlUnosTerminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblDatumPocetka)
								.addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblKapacitet)
								.addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblGrad).addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlUnosTerminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblDatumZavrsetka)
								.addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblBrojCasova)
								.addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblAdresa).addComponent(cmbAdresa, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlUnosTerminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblRaspored)
								.addComponent(txtRaspored, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCena)
								.addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblProfesor).addComponent(cmbProfesor,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(pnlUnosTerminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDodajNoviTermin).addComponent(btnObrisiUnetiTermin)
								.addComponent(btnIzmeniTermin).addComponent(btnPotvrdiIzmene))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(pnlUnetiTermini, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

		btnSacuvaj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		btnSacuvaj.setText("Sacuvaj novi kurs");

		btnOmoguciIzmene.setText("Omoguci izmene");

		btnIzmeniKurs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		btnIzmeniKurs.setText("Izmeni kurs");

		btnUnesiTermine.setText("Unesi termine");

		btnIzaberiTermin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		btnIzaberiTermin.setText("Izaberi termin");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(pnlUnosTermina, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblNaziv).addComponent(lblNivo).addComponent(lblTipKursa)
										.addComponent(lblJezik))
								.addGap(22, 22, 22)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(txtNaziv)
										.addComponent(cmbNivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(cmbTipKursa, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(cmbJezik, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addGap(31, 31, 31).addComponent(btnOmoguciIzmene).addGap(18, 18, 18)
								.addComponent(btnUnesiTermine).addGap(87, 87, 87))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnIzaberiTermin).addGap(18, 18, 18).addComponent(btnIzmeniKurs)
								.addGap(27, 27, 27).addComponent(btnSacuvaj).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblNaziv)
						.addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblNivo)
						.addComponent(cmbNivo, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(lblTipKursa).addComponent(cmbTipKursa, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblJezik)
						.addComponent(cmbJezik, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(btnOmoguciIzmene).addComponent(btnUnesiTermine))
				.addGap(18, 18, 18)
				.addComponent(pnlUnosTermina, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnSacuvaj).addComponent(btnIzmeniKurs))
						.addComponent(btnIzaberiTermin))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnDodajNoviTermin;
	private javax.swing.JButton btnIzaberiTermin;
	private javax.swing.JButton btnIzmeniKurs;
	private javax.swing.JButton btnIzmeniTermin;
	private javax.swing.JButton btnObrisiUnetiTermin;
	private javax.swing.JButton btnOmoguciIzmene;
	private javax.swing.JButton btnPotvrdiIzmene;
	private javax.swing.JButton btnSacuvaj;
	private javax.swing.JButton btnUnesiTermine;
	private javax.swing.JComboBox cmbAdresa;
	private javax.swing.JComboBox cmbGrad;
	private javax.swing.JComboBox cmbJezik;
	private javax.swing.JComboBox cmbNivo;
	private javax.swing.JComboBox cmbProfesor;
	private javax.swing.JComboBox cmbTipKursa;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblAdresa;
	private javax.swing.JLabel lblBrojCasova;
	private javax.swing.JLabel lblCena;
	private javax.swing.JLabel lblDatumPocetka;
	private javax.swing.JLabel lblDatumZavrsetka;
	private javax.swing.JLabel lblGrad;
	private javax.swing.JLabel lblJezik;
	private javax.swing.JLabel lblKapacitet;
	private javax.swing.JLabel lblNaziv;
	private javax.swing.JLabel lblNivo;
	private javax.swing.JLabel lblProfesor;
	private javax.swing.JLabel lblRaspored;
	private javax.swing.JLabel lblTipKursa;
	private javax.swing.JPanel pnlUnetiTermini;
	private javax.swing.JPanel pnlUnosTermina;
	private javax.swing.JTable tblUnetiTermini;
	private javax.swing.JTextField txtBrojCasova;
	private javax.swing.JTextField txtCena;
	private javax.swing.JTextField txtDatumPocetka;
	private javax.swing.JTextField txtDatumZavrsetka;
	private javax.swing.JTextField txtKapacitet;
	private javax.swing.JTextField txtNaziv;
	private javax.swing.JTextField txtRaspored;
	// End of variables declaration

	public JButton getBtnDodajNoviTermin() {
		return btnDodajNoviTermin;
	}

	public JButton getBtnIzmeniKurs() {
		return btnIzmeniKurs;
	}

	public JButton getBtnObrisiUnetiTermin() {
		return btnObrisiUnetiTermin;
	}

	public JButton getBtnSacuvaj() {
		return btnSacuvaj;
	}

	public JButton getBtnOmoguciIzmene() {
		return btnOmoguciIzmene;
	}

	public JComboBox getCmbAdresa() {
		return cmbAdresa;
	}

	public JComboBox getCmbGrad() {
		return cmbGrad;
	}

	public JComboBox getCmbJezik() {
		return cmbJezik;
	}

	public JComboBox getCmbNivo() {
		return cmbNivo;
	}

	public JComboBox getCmbProfesor() {
		return cmbProfesor;
	}

	public JComboBox getCmbTipKursa() {
		return cmbTipKursa;
	}

	public JPanel getPnlUnosTermina() {
		return pnlUnosTermina;
	}

	public JTextField getTxtBrojCasova() {
		return txtBrojCasova;
	}

	public JTextField getTxtCena() {
		return txtCena;
	}

	public JTextField getTxtDatumPocetka() {
		return txtDatumPocetka;
	}

	public JTextField getTxtDatumZavrsetka() {
		return txtDatumZavrsetka;
	}

	public JTextField getTxtKapacitet() {
		return txtKapacitet;
	}

	public JTextField getTxtNaziv() {
		return txtNaziv;
	}

	public JTextField getTxtRaspored() {
		return txtRaspored;
	}

	public JTable getTblUnetiTermini() {
		return tblUnetiTermini;
	}

	public JButton getBtnUnesiTermine() {
		return btnUnesiTermine;
	}

	public JButton getBtnIzmeniTermin() {
		return btnIzmeniTermin;
	}

	public JButton getBtnPotvrdiIzmene() {
		return btnPotvrdiIzmene;
	}

	public JButton getBtnIzaberiTermin() {
		return btnIzaberiTermin;
	}

	public void addBtnUnesiTermineActionListener(ActionListener actionListener) {
		btnUnesiTermine.addActionListener(actionListener);
	}

	public void addBtnOmoguciIzmeneActionListener(ActionListener actionListener) {
		btnOmoguciIzmene.addActionListener(actionListener);
	}

	public void addBtnObrisiActionListener(ActionListener actionListener) {
		btnObrisiUnetiTermin.addActionListener(actionListener);
	}

	public void addBtnDodajActionListener(ActionListener actionListener) {
		btnDodajNoviTermin.addActionListener(actionListener);
	}

	public void addBtnIzmeniTermin(ActionListener actionListener) {
		btnIzmeniTermin.addActionListener(actionListener);
	}

	public void addBtnSacuvajActionListener(ActionListener actionListener) {
		btnSacuvaj.addActionListener(actionListener);
	}

	public void addBtnIzmeniActionListener(ActionListener actionListener) {
		btnIzmeniKurs.addActionListener(actionListener);
	}

	public void addBtnPotvrdiIzmeneActionListener(ActionListener actionListener) {
		btnPotvrdiIzmene.addActionListener(actionListener);
	}

	public void addBtnIzaberiTerminActionListener(ActionListener actionListener) {
		btnIzaberiTermin.addActionListener(actionListener);
	}

}
