package rs.ac.bg.fon.nprog.client.forms;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class FrmProfesor extends JDialog {

	/**
	 * Creates new form FrmProfesor
	 */
	public FrmProfesor(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pnlProfesor = new javax.swing.JPanel();
		lblIme = new javax.swing.JLabel();
		lblPrezime = new javax.swing.JLabel();
		lblTelefon = new javax.swing.JLabel();
		lblEmail = new javax.swing.JLabel();
		lblJezik = new javax.swing.JLabel();
		txtIme = new javax.swing.JTextField();
		txtPrezime = new javax.swing.JTextField();
		txtTelefon = new javax.swing.JTextField();
		txtEmail = new javax.swing.JTextField();
		cmbJezik = new javax.swing.JComboBox();
		btnUnosProfesora = new javax.swing.JButton();
		btnZatvori = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblIme.setText("Ime:");

		lblPrezime.setText("Prezime:");

		lblTelefon.setText("Telefon:");

		lblEmail.setText("Email:");

		lblJezik.setText("Jezik:");

		cmbJezik.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnUnosProfesora.setText("Unesi profesora");

		btnZatvori.setText("Zatvori formu");

		javax.swing.GroupLayout pnlProfesorLayout = new javax.swing.GroupLayout(pnlProfesor);
		pnlProfesor.setLayout(pnlProfesorLayout);
		pnlProfesorLayout.setHorizontalGroup(pnlProfesorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlProfesorLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(pnlProfesorLayout.createSequentialGroup().addGroup(
										pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblIme).addComponent(lblPrezime).addComponent(lblTelefon)
												.addComponent(lblEmail).addComponent(lblJezik))
										.addGap(38, 38, 38)
										.addGroup(pnlProfesorLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtTelefon, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(cmbJezik, 0, 272, Short.MAX_VALUE)))
								.addGroup(pnlProfesorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(btnZatvori, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnUnosProfesora, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
						.addContainerGap(24, Short.MAX_VALUE)));
		pnlProfesorLayout.setVerticalGroup(pnlProfesorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlProfesorLayout.createSequentialGroup().addGap(28, 28, 28)
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(lblIme).addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblPrezime)
								.addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTelefon)
								.addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblEmail).addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblJezik).addComponent(cmbJezik, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
						.addComponent(btnUnosProfesora)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnZatvori)
						.addGap(23, 23, 23)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pnlProfesor,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(pnlProfesor,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnUnosProfesora;
	private javax.swing.JButton btnZatvori;
	private javax.swing.JComboBox cmbJezik;
	private javax.swing.JLabel lblEmail;
	private javax.swing.JLabel lblIme;
	private javax.swing.JLabel lblJezik;
	private javax.swing.JLabel lblPrezime;
	private javax.swing.JLabel lblTelefon;
	private javax.swing.JPanel pnlProfesor;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JTextField txtIme;
	private javax.swing.JTextField txtPrezime;
	private javax.swing.JTextField txtTelefon;
	// End of variables declaration

	public JButton getBtnUnosProfesora() {
		return btnUnosProfesora;
	}

	public JButton getBtnZatvori() {
		return btnZatvori;
	}

	public JTextField getTxtEmail() {
		return txtEmail;
	}

	public JTextField getTxtIme() {
		return txtIme;
	}

	public JTextField getTxtPrezime() {
		return txtPrezime;
	}

	public JTextField getTxtTelefon() {
		return txtTelefon;
	}

	public JPanel getPnlProfesor() {
		return pnlProfesor;
	}

	public JComboBox getCmbJezik() {
		return cmbJezik;
	}

	public void addBtnUnesiActionListener(ActionListener actionListener) {
		btnUnosProfesora.addActionListener(actionListener);
	}

	public void addBtnZatvoriActionListener(ActionListener actionListener) {
		btnZatvori.addActionListener(actionListener);
	}
}
