package rs.ac.bg.fon.nprog.client.forms;

import javax.swing.JButton;
import javax.swing.JDialog;
import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.JTextField;

public class FrmPretragaPolaznika extends JDialog {

	/**
	 * Creates new form FrmPretragaPolaznika
	 */
	public FrmPretragaPolaznika(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(null);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lblIme = new javax.swing.JLabel();
		lblPrezime = new javax.swing.JLabel();
		txtIme = new javax.swing.JTextField();
		txtPrezime = new javax.swing.JTextField();
		btnPretrazi = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPolaznici = new javax.swing.JTable();
		btnDetalji = new javax.swing.JButton();
		btnIzaberi = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Pretraga polaznika");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretrazi polaznike"));

		lblIme.setText("Ime:");

		lblPrezime.setText("Prezime:");

		btnPretrazi.setText("Pretrazi");

		tblPolaznici
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblPolaznici);

		btnDetalji.setText("Detalji");

		btnIzaberi.setText("Izaberi polaznika");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblIme).addComponent(lblPrezime))
								.addGap(24, 24, 24)
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 241,
												Short.MAX_VALUE)
										.addComponent(txtPrezime))
								.addGap(32, 32, 32).addComponent(btnPretrazi).addGap(0, 0, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
										.addComponent(btnIzaberi)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnDetalji)))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(34, 34, 34).addComponent(btnPretrazi))
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19).addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblIme)
								.addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(lblPrezime).addComponent(txtPrezime,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDetalji).addComponent(btnIzaberi))
						.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnDetalji;
	private javax.swing.JButton btnIzaberi;
	private javax.swing.JButton btnPretrazi;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblIme;
	private javax.swing.JLabel lblPrezime;
	private javax.swing.JTable tblPolaznici;
	private javax.swing.JTextField txtIme;
	private javax.swing.JTextField txtPrezime;
	// End of variables declaration

	public JButton getBtnDetalji() {
		return btnDetalji;
	}

	public JButton getBtnPretrazi() {
		return btnPretrazi;
	}

	public JTable getTblPolaznici() {
		return tblPolaznici;
	}

	public JTextField getTxtIme() {
		return txtIme;
	}

	public JTextField getTxtPrezime() {
		return txtPrezime;
	}

	public JButton getBtnIzaberi() {
		return btnIzaberi;
	}

	public void addBtnDetaljiActionListener(ActionListener actionListener) {
		btnDetalji.addActionListener(actionListener);
	}

	public void addBtnPretraziActionListener(ActionListener actionListener) {
		btnPretrazi.addActionListener(actionListener);
	}

	public void addBtnIzaberiActionListener(ActionListener actionListener) {
		btnIzaberi.addActionListener(actionListener);
	}

}
