package rs.ac.bg.fon.nprog.client.forms;

import javax.swing.JButton;
import javax.swing.JDialog;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

public class FrmPretragaProfesora extends JDialog {

	/**
	 * Creates new form FrmPretragaProfesora
	 */
	public FrmPretragaProfesora(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pnlPretragaProf = new javax.swing.JPanel();
		lblIme = new javax.swing.JLabel();
		lblPrezime = new javax.swing.JLabel();
		lblJezik = new javax.swing.JLabel();
		txtIme = new javax.swing.JTextField();
		txtPrezime = new javax.swing.JTextField();
		cmbJezik = new javax.swing.JComboBox();
		btnPretrazi = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblProfesori = new javax.swing.JTable();
		btnDetalji = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Pretraga profesora");

		pnlPretragaProf.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretrazi profesore"));

		lblIme.setText("Ime:");

		lblPrezime.setText("Prezime:");

		lblJezik.setText("Jezik:");

		cmbJezik.setModel(
				new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		btnPretrazi.setText("Pretrazi");

		tblProfesori
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tblProfesori);

		btnDetalji.setText("Detalji");

		javax.swing.GroupLayout pnlPretragaProfLayout = new javax.swing.GroupLayout(pnlPretragaProf);
		pnlPretragaProf.setLayout(pnlPretragaProfLayout);
		pnlPretragaProfLayout.setHorizontalGroup(pnlPretragaProfLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPretragaProfLayout.createSequentialGroup().addContainerGap().addGroup(pnlPretragaProfLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								pnlPretragaProfLayout.createSequentialGroup()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487,
												Short.MAX_VALUE)
										.addContainerGap())
						.addGroup(pnlPretragaProfLayout.createSequentialGroup().addGroup(
								pnlPretragaProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblIme).addComponent(lblPrezime).addComponent(lblJezik))
								.addGap(37, 37, 37)
								.addGroup(pnlPretragaProfLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(pnlPretragaProfLayout.createSequentialGroup()
												.addGroup(pnlPretragaProfLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtPrezime)
														.addComponent(cmbJezik, 0, 248, Short.MAX_VALUE))
												.addGap(28, 28, 28).addComponent(btnPretrazi))
										.addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(0, 0, Short.MAX_VALUE))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						pnlPretragaProfLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnDetalji).addContainerGap()));
		pnlPretragaProfLayout.setVerticalGroup(pnlPretragaProfLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlPretragaProfLayout.createSequentialGroup().addGap(16, 16, 16)
						.addGroup(pnlPretragaProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblIme).addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlPretragaProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlPretragaProfLayout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(pnlPretragaProfLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(lblPrezime)
												.addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(pnlPretragaProfLayout.createSequentialGroup().addGap(3, 3, 3)
										.addComponent(btnPretrazi)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlPretragaProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblJezik).addComponent(cmbJezik, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(btnDetalji)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(pnlPretragaProf,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(pnlPretragaProf, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnDetalji;
	private javax.swing.JButton btnPretrazi;
	private javax.swing.JComboBox cmbJezik;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblIme;
	private javax.swing.JLabel lblJezik;
	private javax.swing.JLabel lblPrezime;
	private javax.swing.JPanel pnlPretragaProf;
	private javax.swing.JTable tblProfesori;
	private javax.swing.JTextField txtIme;
	private javax.swing.JTextField txtPrezime;
	// End of variables declaration

	public JButton getBtnDetalji() {
		return btnDetalji;
	}

	public JButton getBtnPretrazi() {
		return btnPretrazi;
	}

	public JComboBox getCmbJezik() {
		return cmbJezik;
	}

	public JTable getTblProfesori() {
		return tblProfesori;
	}

	public JTextField getTxtIme() {
		return txtIme;
	}

	public JTextField getTxtPrezime() {
		return txtPrezime;
	}

	public void addBtnDetaljiActionListener(ActionListener actionListener) {
		btnDetalji.addActionListener(actionListener);
	}

	public void addBtnPretraziActionListener(ActionListener actionListener) {
		btnPretrazi.addActionListener(actionListener);
	}

}
