package rs.ac.bg.fon.nprog.client.forms;



import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import javax.swing.JTextField;



public class FrmPolaznik extends JDialog {

	/**
     * Creates new form FrmPolaznik
     */
    public FrmPolaznik(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlPolaznik = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblJMBG = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblEMail = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtEMail = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        btnUnesiPolaznika = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPolaznik.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblIme.setText("Ime:");

        lblPrezime.setText("Prezime:");

        lblJMBG.setText("JMBG:");

        lblTelefon.setText("Telefon:");

        lblEMail.setText("EMail:");

        lblAdresa.setText("Adresa:");

        btnUnesiPolaznika.setText("Unesi polaznika");

        btnZatvori.setText("Zatvori formu");

        javax.swing.GroupLayout pnlPolaznikLayout = new javax.swing.GroupLayout(pnlPolaznik);
        pnlPolaznik.setLayout(pnlPolaznikLayout);
        pnlPolaznikLayout.setHorizontalGroup(
            pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolaznikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolaznikLayout.createSequentialGroup()
                        .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIme)
                            .addComponent(lblPrezime)
                            .addComponent(lblJMBG)
                            .addComponent(lblTelefon)
                            .addComponent(lblEMail)
                            .addComponent(lblAdresa))
                        .addGap(41, 41, 41)
                        .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime)
                            .addComponent(txtJMBG)
                            .addComponent(txtTelefon)
                            .addComponent(txtEMail)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolaznikLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUnesiPolaznika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZatvori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlPolaznikLayout.setVerticalGroup(
            pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolaznikLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJMBG)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEMail)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPolaznikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresa)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUnesiPolaznika)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZatvori)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

 

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnUnesiPolaznika;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblEMail;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblJMBG;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JPanel pnlPolaznik;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtEMail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration                   

    public JButton getBtnUnesiPolaznika() {
        return btnUnesiPolaznika;
    }

    public void setBtnUnesiPolaznika(JButton btnUnesiPolaznika) {
        this.btnUnesiPolaznika = btnUnesiPolaznika;
    }

    public JButton getBtnZatvori() {
        return btnZatvori;
    }

    public void setBtnZatvori(JButton btnZatvori) {
        this.btnZatvori = btnZatvori;
    }

    public JTextField getTxtAdresa() {
        return txtAdresa;
    }

    public void setTxtAdresa(JTextField txtAdresa) {
        this.txtAdresa = txtAdresa;
    }

    public JTextField getTxtEMail() {
        return txtEMail;
    }

    public void setTxtEMail(JTextField txtEMail) {
        this.txtEMail = txtEMail;
    }

    public JTextField getTxtIme() {
        return txtIme;
    }

    public void setTxtIme(JTextField txtIme) {
        this.txtIme = txtIme;
    }

    public JTextField getTxtJMBG() {
        return txtJMBG;
    }

    public void setTxtJMBG(JTextField txtJMBG) {
        this.txtJMBG = txtJMBG;
    }

    public JTextField getTxtPrezime() {
        return txtPrezime;
    }

    public void setTxtPrezime(JTextField txtPrezime) {
        this.txtPrezime = txtPrezime;
    }

    public JTextField getTxtTelefon() {
        return txtTelefon;
    }

    public void setTxtTelefon(JTextField txtTelefon) {
        this.txtTelefon = txtTelefon;
    }

    public JPanel getPnlPolaznik() {
        return pnlPolaznik;
    }

    public void addBtnUnesiActionListener(ActionListener actionListener){
        btnUnesiPolaznika.addActionListener(actionListener);
    }
    
    public void addBtnZatvoriActionListener(ActionListener actionListener){
        btnZatvori.addActionListener(actionListener);
    }

}
